### ISSUE TITLE
Deployment on Heroku

### ISSUE THREAD

**Issue by Btibert3** [magnusfurugard/nlg-markovify-api#1]
Have you written about this as a blog post anywhere?  I just came across this repo and would love to see how you deployed this to Heroku.  I wasn't aware of the NLG packages, so thanks for wrapping this around plumber.  Very cool to see a worked example.

**Comment by praktiskt** [comment]
I'm glad you liked it. I decided to take your advice and write a blog post on it. You can find it [here](https://medium.com/@magnus.furugard/r-docker-heroku-rest-api-30c351f9c194).
